---
- name: Win CNI | Install PSCX
  win_psmodule:
    name: Pscx
    state: present
    allow_clobber: true

- name: Win CNI | Ensure CNI directories exist
  win_file:
    path: "{{ item }}"
    state: directory
    recurse: true
  loop:
    - "{{ win_cni_bin_dir }}"
    - "{{ win_cni_conf_dir }}"

- name: Win CNI | Download CNI package 
  win_get_url:
    url: "{{ win_cni_plugins_release_url }}"
    dest: "{{ win_cni_bin_dir }}/{{ win_cni_plugins_release_url | basename }}"
    force: true

- name: Win CNI | extract CNI plugins binaries tgz
  win_unzip:
    src: "{{ win_cni_bin_dir }}/{{ win_cni_plugins_release_url | basename }}"
    dest: "{{ win_cni_bin_dir }}"
    recurse: true

- name: Win CNI | extract CNI plugins binaries tar
  win_unzip:
    src: "{{ win_cni_bin_dir }}/{{ (win_cni_plugins_release_url | basename | splitext)[0] }}.tar"
    dest: "{{ win_cni_bin_dir }}"
    recurse: true
    creates: "{{ win_cni_bin_dir }}/flannel.exe"
